[package]
name = "aoc2020"
version = "1.0.0"
authors = ["Jo√£o Conde <joaodiasconde@gmail.com>"]
edition = "2018"
default-run = "aoc2020"

[dependencies]
regex = "1"
itertools = "0.9"

[profile.release]
opt-level = 3
